DROP TABLE IF EXISTS TOOLS;

CREATE TABLE TOOLS (
    TOOL_CODE VARCHAR(20) PRIMARY KEY,
    TOOL_TYPE VARCHAR(100) NOT NULL,
    BRAND VARCHAR(100) NOT NULL
);

INSERT INTO TOOLS (TOOL_CODE, TOOL_TYPE, BRAND) VALUES 
('LADW', 'Ladder', 'Werner'),
('CHNS', 'Chainsaw', 'Stihl'),
('JAKR', 'Jackhammer', 'Ridgid'),
('JAKD', 'Jackhammer', 'DeWalt');


DROP TABLE IF EXISTS TOOL_CHARGES;

CREATE TABLE TOOL_CHARGES (
    TOOL_TYPE VARCHAR(100) PRIMARY KEY,
    DAILY_CHARGE DECIMAL NOT NULL,
    WEEKDAY_CHARGE VARCHAR(20) NOT NULL,
    WEEKEND_CHARGE VARCHAR(20) NOT NULL,
    HOLIDAY_CHARGE VARCHAR(20) NOT NULL
);

INSERT INTO TOOL_CHARGES (TOOL_TYPE, DAILY_CHARGE, WEEKDAY_CHARGE, WEEKEND_CHARGE, HOLIDAY_CHARGE) VALUES 
('Ladder', 1.99, 'Yes', 'Yes', 'No'),
('Chainsaw', 1.49, 'Yes', 'No', 'Yes'),
('Jackhammer', 2.99, 'Yes', 'No', 'No');